# -*- coding: utf-8 -*-
{
    "name": "Sale Order Export Sheet",
    "summary": "Export selected sale orders to a structured Excel spreadsheet",
    "version": "16.0.1.0.0",
    "category": "Sales",
    "author": "Generated by ChatGPT",
    "license": "LGPL-3",
    "depends": ["sale_management"],
    "data": [
        "views/sale_order_export_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
}
